import type { RestaurantSeed } from "./types";

export const dsSports: RestaurantSeed = {
  slug: "ds-sports",
  menus: [
    {
      service: "All Day",
      sections: [
        {
          name: "Starters",
          items: [
            { name: "Spinach Artichoke Dip" },
            { name: "Steakhouse Chili Dip" },
            { name: "Wagyu Empanadas" },
            { name: "Chicken Nuggets & Caviar" },
            { name: "Crispy Calamari" },
            { name: "Sausage Parm" },
            { name: "Wagyu Meatballs" },
          ],
        },
        {
          name: "Salads",
          items: [
            { name: "Classic Caesar Salad" },
            { name: "Wedge Salad" },
          ],
        },
        {
          name: "Wings",
          items: [
            { name: "Chicken Wings (6pc)", components: ["traditional or boneless", "buffalo / BBQ / garlic parm / dry rub"] },
          ],
        },
        {
          name: "Sandwiches & Burgers",
          items: [
            { name: "The Heritage Burger" },
            { name: "Daniel's Double Patty Smash Burger", components: ["Florida beef", "bacon", "American cheese", "smash sauce", "brioche"] },
            { name: "Daniel's Florida Grassfed Burger" },
            { name: "D's French Dip Steak Sandwich", components: ["sliced steak", "provolone", "onion au jus", "hoagie roll"] },
            { name: "Mr. A's Chicken Milanese Hoagie" },
            { name: "Housemade Pastrami Reuben" },
            { name: "Snake River All Beef Hot Dog (Chicago Style)" },
          ],
        },
        {
          name: "Entrées",
          items: [
            { name: "Grilled Branzino" },
            { name: "Shrimp Scampi Pasta" },
            { name: "Chicken Parm" },
            { name: "Demkota Prime Filet Mignon" },
            { name: "Upper Iowa NY Strip" },
            { name: "Stone Axe Wagyu Denver Steak" },
            { name: "Greater Omaha Cowboy Ribeye" },
          ],
        },
        {
          name: "Sides",
          items: [
            { name: "Rosemary French Fries" },
            { name: "Cacio e Pepe Tater Tots" },
            { name: "Brussel Sprouts Agrodolce" },
            { name: "Broccolini" },
          ],
        },
        {
          name: "Dessert",
          items: [
            { name: "Red Velvet Cake" },
            { name: "Brownie Sundae" },
            { name: "Fried Oreos" },
          ],
        },
        {
          name: "Cocktails",
          items: [
            { name: "Rio Spritz" },
            { name: "D's Margarita" },
            { name: "Old Smokey", components: ["Fiola Cask Bourbon", "smoked"] },
            { name: "Tropical Rumjito" },
            { name: "The Staycation" },
            { name: "Dano's Dangerous Espresso Martini" },
          ],
        },
        {
          name: "Beer & Seltzer",
          items: [
            { name: "Drafts (6 rotating)", components: ["Gulfstream Brewing", "Funky Buddha"] },
            { name: "Bottled Beer (6)" },
            { name: "Seltzers (3)" },
          ],
        },
      ],
    },
  ],
  stations: [
    {
      name: "Walk-in Cooler — Burgers & Proteins",
      sortOrder: 1,
      items: [
        { name: "Florida Grassfed Burger Patties (smash)", unit: "lb", par: 30, category: "Beef" },
        { name: "Heritage Burger Patties", unit: "each", par: 40, category: "Beef" },
        { name: "Suwannee Wagyu Empanada Filling", unit: "lb", par: 10, category: "Beef" },
        { name: "Wagyu Meatball Mix", unit: "lb", par: 10, category: "Beef" },
        { name: "Chili Dip Beef (cooked, batch)", unit: "lb", par: 20, category: "Prep" },
        { name: "House Pastrami", unit: "lb", par: 8, category: "Charcuterie" },
        { name: "French Dip Steak (sliced)", unit: "lb", par: 12, category: "Beef" },
        { name: "Demkota Filet Mignon", unit: "each", par: 16, category: "Beef" },
        { name: "Upper Iowa NY Strip", unit: "lb", par: 8, category: "Beef" },
        { name: "Stone Axe Denver Steak", unit: "lb", par: 6, category: "Beef" },
        { name: "Greater Omaha Cowboy Ribeye", unit: "each", par: 6, category: "Beef" },
        { name: "Chicken Wings", unit: "lb", par: 30, category: "Poultry" },
        { name: "Chicken Breast (parm / milanese)", unit: "lb", par: 15, category: "Poultry" },
        { name: "Chicken Nuggets", unit: "lb", par: 12, category: "Poultry" },
        { name: "Sunshine Fennel Sausage", unit: "lb", par: 6, category: "Charcuterie" },
        { name: "Snake River All Beef Hot Dogs", unit: "each", par: 48, category: "Charcuterie" },
        { name: "Bacon", unit: "lb", par: 15, category: "Charcuterie" },
      ],
    },
    {
      name: "Walk-in Cooler — Seafood",
      sortOrder: 2,
      items: [
        { name: "Branzino", unit: "each", par: 10, category: "Fish" },
        { name: "Shrimp (scampi 21-25)", unit: "lb", par: 12, category: "Shellfish" },
        { name: "Calamari (cleaned tubes)", unit: "lb", par: 12, category: "Shellfish" },
        { name: "Crispy Hogfish (if running)", unit: "lb", par: 6, category: "Fish" },
        { name: "Kaluga Caviar (nugget service)", unit: "oz", par: 4, category: "Caviar" },
      ],
    },
    {
      name: "Walk-in Cooler — Dairy & Produce",
      sortOrder: 3,
      items: [
        { name: "American Cheese (smash)", unit: "lb", par: 8, category: "Cheese" },
        { name: "Provolone", unit: "lb", par: 6, category: "Cheese" },
        { name: "Mozzarella (chicken parm)", unit: "lb", par: 6, category: "Cheese" },
        { name: "Parmigiano Reggiano", unit: "lb", par: 5, category: "Cheese" },
        { name: "Cheddar (chili dip)", unit: "lb", par: 4, category: "Cheese" },
        { name: "Cream Cheese (spin artichoke)", unit: "lb", par: 4, category: "Cheese" },
        { name: "Hawthorne Creamery Blue Cheese", unit: "lb", par: 3, category: "Cheese" },
        { name: "Butter", unit: "lb", par: 10, category: "Dairy" },
        { name: "Heavy Cream", unit: "qt", par: 4, category: "Dairy" },
        { name: "Whole Milk", unit: "gal", par: 3, category: "Dairy" },
        { name: "Sour Cream", unit: "qt", par: 3, category: "Dairy" },
        { name: "Eggs", unit: "case", par: 3, category: "Dairy" },
        { name: "Romaine (Caesar)", unit: "case", par: 2, category: "Produce" },
        { name: "Iceberg (wedge)", unit: "case", par: 2, category: "Produce" },
        { name: "Tomatoes (slicer)", unit: "case", par: 2, category: "Produce" },
        { name: "Yellow Onions", unit: "case", par: 2, category: "Produce" },
        { name: "Red Onions", unit: "case", par: 1, category: "Produce" },
        { name: "Brussels Sprouts", unit: "lb", par: 12, category: "Produce" },
        { name: "Broccolini", unit: "lb", par: 12, category: "Produce" },
        { name: "Spinach", unit: "lb", par: 8, category: "Produce" },
        { name: "Artichoke Hearts", unit: "lb", par: 8, category: "Produce" },
        { name: "Lemons", unit: "case", par: 2, category: "Produce" },
        { name: "Pickles", unit: "gal", par: 4, category: "Produce" },
        { name: "Idaho Potatoes (fries)", unit: "case", par: 4, category: "Produce" },
        { name: "Garlic", unit: "lb", par: 3, category: "Produce" },
        { name: "Parsley", unit: "lb", par: 1, category: "Herbs" },
        { name: "Rosemary", unit: "lb", par: 1, category: "Herbs" },
        { name: "Basil", unit: "lb", par: 1, category: "Herbs" },
      ],
    },
    {
      name: "Walk-in Freezer",
      sortOrder: 4,
      items: [
        { name: "Brioche Buns", unit: "case", par: 4 },
        { name: "Hoagie Rolls", unit: "case", par: 2 },
        { name: "Hot Dog Buns", unit: "case", par: 2 },
        { name: "Tater Tots", unit: "case", par: 4 },
        { name: "Fried Oreos (batter or pre-batt)", unit: "case", par: 2 },
        { name: "Brownie Base", unit: "case", par: 1 },
        { name: "Ice Cream — Vanilla", unit: "gal", par: 4 },
        { name: "Empanada Dough", unit: "case", par: 2 },
      ],
    },
    {
      name: "Dry Storage",
      sortOrder: 5,
      items: [
        { name: "Fryer Oil", unit: "gal", par: 10, category: "Oils" },
        { name: "EVOO", unit: "l", par: 4, category: "Oils" },
        { name: "Canola Blend", unit: "gal", par: 6, category: "Oils" },
        { name: "Marinara (batch)", unit: "qt", par: 8, category: "Sauces" },
        { name: "Au Jus Base", unit: "qt", par: 6, category: "Sauces" },
        { name: "Smash Sauce", unit: "qt", par: 6, category: "Sauces" },
        { name: "BBQ Sauce", unit: "qt", par: 4, category: "Sauces" },
        { name: "Buffalo Sauce", unit: "qt", par: 6, category: "Sauces" },
        { name: "Ketchup", unit: "gal", par: 4, category: "Sauces" },
        { name: "Mustard", unit: "gal", par: 2, category: "Sauces" },
        { name: "Mayo", unit: "gal", par: 4, category: "Sauces" },
        { name: "Spaghetti", unit: "lb", par: 20, category: "Pasta" },
        { name: "Penne", unit: "lb", par: 12, category: "Pasta" },
        { name: "Tater Tot Seasoning (Cacio e Pepe)", unit: "lb", par: 3, category: "Pantry" },
        { name: "Panko / Breadcrumbs", unit: "lb", par: 10, category: "Pantry" },
        { name: "Flour", unit: "lb", par: 50, category: "Baking" },
        { name: "Sugar", unit: "lb", par: 20, category: "Baking" },
        { name: "Espresso Beans", unit: "lb", par: 4, category: "Beverage" },
      ],
    },
    {
      name: "Bar — Liquor",
      sortOrder: 6,
      items: [
        { name: "Fiola Cask Bourbon", unit: "bottle", par: 6 },
        { name: "Tito's Vodka", unit: "bottle", par: 8 },
        { name: "Tequila Blanco", unit: "bottle", par: 6 },
        { name: "Mezcal", unit: "bottle", par: 3 },
        { name: "Bacardi Rum", unit: "bottle", par: 4 },
        { name: "Gin", unit: "bottle", par: 4 },
        { name: "Aperol", unit: "bottle", par: 4 },
        { name: "Sweet/Dry Vermouth", unit: "bottle", par: 4 },
        { name: "Espresso Liqueur (Kahlúa)", unit: "bottle", par: 4 },
      ],
    },
    {
      name: "Bar — Beer & Seltzer",
      sortOrder: 7,
      items: [
        { name: "Gulfstream Brewing (keg)", unit: "each", par: 2 },
        { name: "Funky Buddha (keg)", unit: "each", par: 2 },
        { name: "Rotating Draft (kegs)", unit: "each", par: 2 },
        { name: "Domestic Bottles", unit: "case", par: 8 },
        { name: "Import Bottles", unit: "case", par: 4 },
        { name: "Seltzer — Variety", unit: "case", par: 6 },
        { name: "BTG Red (sports list)", unit: "bottle", par: 12 },
        { name: "BTG White (sports list)", unit: "bottle", par: 12 },
      ],
    },
    {
      name: "Bar — Garnish & Mixers",
      sortOrder: 8,
      items: [
        { name: "Limes", unit: "case", par: 2 },
        { name: "Lemons", unit: "case", par: 2 },
        { name: "Oranges", unit: "case", par: 1 },
        { name: "Simple Syrup", unit: "qt", par: 6 },
        { name: "Tonic Water", unit: "case", par: 4 },
        { name: "Club Soda", unit: "case", par: 4 },
        { name: "Coca-Cola (gun line)", unit: "case", par: 6 },
        { name: "Cherries (Luxardo)", unit: "qt", par: 2 },
        { name: "Olives", unit: "qt", par: 3 },
        { name: "Mint", unit: "lb", par: 1 },
      ],
    },
  ],
};
