import type { RestaurantSeed } from "./types";

export const fortLauderdale: RestaurantSeed = {
  slug: "fort-lauderdale",
  menus: [
    {
      service: "Dinner",
      sections: [
        {
          name: "Caviar & Snacks",
          items: [
            { name: "Sullivan Street Sourdough Bread", price: "$11" },
            { name: "Chips & Dip", price: "$49", components: ["Umai Kaluga", "house chips", "caramelized onion", "sour cream", "chives"] },
            { name: "N25 Umai Kaluga Caviar", price: "$85" },
            { name: "N25 Ossetra Caviar", price: "$225" },
          ],
        },
        {
          name: "Soup & Salads",
          items: [
            { name: "Loxahatchee Baby Romaine Basil Caesar", price: "$25", components: ["baby romaine", "basil", "anchovy", "lemon", "croutons", "Piave Vecchio"] },
            { name: "Farmer Mike's Iceberg Wedge", price: "$25", components: ["iceberg", "bacon", "tomatoes", "crispy onions", "Valdeón dressing"] },
            { name: "Florida Seafood Chowder", price: "$29" },
          ],
        },
        {
          name: "Appetizers",
          items: [
            { name: "Florida Oyster Rockefeller", price: "$34" },
            { name: "Serenoa Skipper Sweet Oysters", price: "$28" },
            { name: "Hamachi Crudo & Strawberries", price: "$28" },
            { name: "Black Tiger Prawns", price: "$36" },
            { name: "Wagyu & Pearls", price: "$38", components: ["Arrowhead wagyu tartare", "Kaluga caviar", "sourdough"] },
            { name: "Foie Gras Crème Brûlée", price: "$32" },
            { name: "Pastrami & Bao Buns", price: "$24" },
            { name: "Sausage & Peppers", price: "$28" },
            { name: "Arrowhead Wagyu Meatball", price: "$32" },
            { name: "Florida Blue Crab Cake", price: "$39" },
          ],
        },
        {
          name: "Pasta",
          items: [
            { name: "Orecchiette Pugliese", price: "$48" },
            { name: "Lobster Fra Diavolo", price: "$88" },
          ],
        },
        {
          name: "Land + Seafood",
          items: [
            { name: "Farmer Mike's Zucchini Tataki", price: "$35" },
            { name: "Florida Keys Red Snapper", price: "$46" },
            { name: "Grilled Canary Island Aquanaria Branzino", price: "$72" },
            { name: "Providence Cattle Braised Beef Short Rib", price: "$58" },
          ],
        },
        {
          name: "Steak & Chops",
          items: [
            { name: "Gundagai Australian Lamb Chops", price: "$76" },
            { name: "Demkota Prime Filet Mignon (8oz)", price: "$78" },
            { name: "Florida Quincey Cattle Filet Mignon (12oz)", price: "$95" },
            { name: "Upper Iowa Prime NY Strip (16oz)", price: "$95" },
            { name: "Providence Grassfed Kansas City (20oz)", price: "$105" },
            { name: "Margaret River Wagyu NY Strip (14oz)", price: "$135" },
            { name: "Arrowhead Wagyu Delmonico Ribeye (14oz)", price: "$140" },
            { name: "Creekstone Dry-Aged Prime Cowboy Ribeye (22oz)", price: "$155" },
            { name: "Demkota Prime Porterhouse (32oz)", price: "$225" },
            { name: "Texas Rosewood Wagyu Porterhouse (32oz)", price: "$375" },
            { name: "Stone Axe Full-Blooded Wagyu Tomahawk", price: "MP" },
          ],
        },
        {
          name: "Sides",
          items: [
            { name: "Grilled Asparagus", price: "$19" },
            { name: "Florida Rosemary Fries", price: "$14" },
            { name: "Creamed Spinach", price: "$18" },
            { name: "Corn Pudding", price: "$17" },
            { name: "Twice Baked Potato", price: "$18" },
            { name: "Crimini Mushrooms", price: "$19" },
            { name: "Maine Lobster Mac & Cheese", price: "$42" },
            { name: "Mezze Rigate Vodka Pasta", price: "$22" },
            { name: "Truffled Potato Fonduta", price: "$34" },
          ],
        },
        {
          name: "Dessert",
          items: [
            { name: "Key Lime Pie", price: "$20" },
            { name: "Red Velvet Cake", price: "$20" },
            { name: "Valrhona Chocolate Chip Cookie Skillet", price: "$20" },
            { name: "Soft Serve Sundae", price: "$21" },
          ],
        },
      ],
    },
  ],
  stations: [
    {
      name: "Walk-in Cooler — Proteins",
      sortOrder: 1,
      items: [
        { name: "Demkota Prime Filet Mignon (8oz)", unit: "each", par: 24, category: "Beef" },
        { name: "Quincey Cattle Filet Mignon (12oz)", unit: "each", par: 12, category: "Beef" },
        { name: "Upper Iowa Prime NY Strip", unit: "lb", par: 15, category: "Beef" },
        { name: "Providence Grassfed Kansas City", unit: "lb", par: 10, category: "Beef" },
        { name: "Margaret River Wagyu NY Strip", unit: "lb", par: 8, category: "Beef" },
        { name: "Arrowhead Wagyu Delmonico", unit: "lb", par: 6, category: "Beef" },
        { name: "Creekstone Dry-Aged Cowboy Ribeye", unit: "each", par: 10, category: "Beef" },
        { name: "Demkota Prime Porterhouse", unit: "each", par: 6, category: "Beef" },
        { name: "Rosewood Wagyu Porterhouse", unit: "each", par: 3, category: "Beef" },
        { name: "Stone Axe Wagyu Tomahawk", unit: "each", par: 4, category: "Beef" },
        { name: "Gundagai Lamb Chops", unit: "lb", par: 8, category: "Lamb" },
        { name: "Providence Short Rib", unit: "lb", par: 10, category: "Beef" },
        { name: "Arrowhead Wagyu (tartare)", unit: "lb", par: 4, category: "Beef" },
        { name: "House Pastrami", unit: "lb", par: 4, category: "Charcuterie" },
        { name: "Hudson Valley Foie Gras", unit: "lb", par: 3, category: "Specialty" },
        { name: "Fennel Sausage", unit: "lb", par: 4, category: "Charcuterie" },
      ],
    },
    {
      name: "Walk-in Cooler — Seafood & Raw Bar",
      sortOrder: 2,
      items: [
        { name: "Serenoa Skipper Sweet Oysters", unit: "case", par: 4, category: "Shellfish" },
        { name: "Black Tiger Prawns", unit: "lb", par: 6, category: "Shellfish" },
        { name: "Maine Lobster (1.5 lb)", unit: "each", par: 12, category: "Shellfish" },
        { name: "Florida Blue Crab Meat", unit: "lb", par: 4, category: "Shellfish" },
        { name: "Hamachi", unit: "lb", par: 3, category: "Fish" },
        { name: "Florida Keys Red Snapper", unit: "lb", par: 6, category: "Fish" },
        { name: "Aquanaria Branzino", unit: "each", par: 12, category: "Fish" },
        { name: "Chowder Fish Blend", unit: "lb", par: 8, category: "Fish" },
        { name: "Umai Kaluga Caviar", unit: "oz", par: 8, category: "Caviar" },
        { name: "N25 Ossetra Caviar", unit: "oz", par: 4, category: "Caviar" },
      ],
    },
    {
      name: "Walk-in Cooler — Dairy & Produce",
      sortOrder: 3,
      items: [
        { name: "Parmigiano Reggiano", unit: "lb", par: 8, category: "Cheese" },
        { name: "Piave Vecchio", unit: "lb", par: 2, category: "Cheese" },
        { name: "Valdeón Blue Cheese", unit: "lb", par: 2, category: "Cheese" },
        { name: "Gruyère", unit: "lb", par: 4, category: "Cheese" },
        { name: "Aged Cheddar", unit: "lb", par: 4, category: "Cheese" },
        { name: "Provolone", unit: "lb", par: 2, category: "Cheese" },
        { name: "Crème Fraîche", unit: "qt", par: 2, category: "Dairy" },
        { name: "Sour Cream", unit: "qt", par: 3, category: "Dairy" },
        { name: "Cultured Butter", unit: "lb", par: 6, category: "Dairy" },
        { name: "Heavy Cream", unit: "qt", par: 5, category: "Dairy" },
        { name: "Whole Milk", unit: "gal", par: 4, category: "Dairy" },
        { name: "Eggs", unit: "case", par: 3, category: "Dairy" },
        { name: "Loxahatchee Baby Romaine", unit: "case", par: 2, category: "Produce" },
        { name: "Iceberg Lettuce", unit: "case", par: 1, category: "Produce" },
        { name: "Cherry Tomatoes", unit: "case", par: 1, category: "Produce" },
        { name: "Heirloom Tomatoes", unit: "case", par: 1, category: "Produce" },
        { name: "Farmer Mike's Zucchini", unit: "case", par: 1, category: "Produce" },
        { name: "Asparagus", unit: "lb", par: 10, category: "Produce" },
        { name: "Crimini Mushrooms", unit: "lb", par: 8, category: "Produce" },
        { name: "Spinach", unit: "lb", par: 8, category: "Produce" },
        { name: "Florida Sweet Corn", unit: "case", par: 1, category: "Produce" },
        { name: "Idaho Potatoes", unit: "case", par: 2, category: "Produce" },
        { name: "Black Winter Truffle", unit: "oz", par: 3, category: "Specialty" },
        { name: "Lemons", unit: "case", par: 2, category: "Produce" },
        { name: "Strawberries", unit: "case", par: 1, category: "Produce" },
        { name: "Bell Peppers", unit: "case", par: 1, category: "Produce" },
        { name: "Yellow Onions", unit: "case", par: 1, category: "Produce" },
        { name: "Garlic", unit: "lb", par: 3, category: "Produce" },
        { name: "Basil", unit: "lb", par: 1, category: "Herbs" },
        { name: "Parsley", unit: "lb", par: 1, category: "Herbs" },
        { name: "Chives", unit: "lb", par: 1, category: "Herbs" },
        { name: "Rosemary", unit: "lb", par: 1, category: "Herbs" },
      ],
    },
    {
      name: "Walk-in Freezer",
      sortOrder: 4,
      items: [
        { name: "Sullivan Street Sourdough", unit: "case", par: 2 },
        { name: "Bao Buns", unit: "case", par: 1 },
        { name: "Soft Serve Mix", unit: "gal", par: 3 },
        { name: "Vanilla Ice Cream", unit: "gal", par: 3 },
      ],
    },
    {
      name: "Dry Storage",
      sortOrder: 5,
      items: [
        { name: "GIOIA EVOO", unit: "l", par: 10, category: "Oils" },
        { name: "Canola Blend", unit: "gal", par: 6, category: "Oils" },
        { name: "Truffle Oil", unit: "l", par: 1, category: "Oils" },
        { name: "Balsamico di Modena", unit: "l", par: 2, category: "Vinegars" },
        { name: "Red Wine Vinegar", unit: "l", par: 2, category: "Vinegars" },
        { name: "Orecchiette", unit: "lb", par: 16, category: "Pasta" },
        { name: "Lumachine", unit: "lb", par: 12, category: "Pasta" },
        { name: "Mezze Rigate", unit: "lb", par: 16, category: "Pasta" },
        { name: "Linguine", unit: "lb", par: 12, category: "Pasta" },
        { name: "Anchovies", unit: "lb", par: 2, category: "Pantry" },
        { name: "Capers", unit: "lb", par: 2, category: "Pantry" },
        { name: "Black Peppercorn", unit: "lb", par: 2, category: "Spices" },
        { name: "Sea Salt", unit: "lb", par: 10, category: "Spices" },
        { name: "All-Purpose Flour", unit: "lb", par: 50, category: "Baking" },
        { name: "Sugar", unit: "lb", par: 25, category: "Baking" },
        { name: "Vanilla Extract", unit: "qt", par: 1, category: "Baking" },
      ],
    },
    {
      name: "Bar — Liquor",
      sortOrder: 6,
      items: [
        { name: "Grey Goose Vodka", unit: "bottle", par: 6 },
        { name: "Tito's Vodka", unit: "bottle", par: 8 },
        { name: "Bombay Sapphire Gin", unit: "bottle", par: 4 },
        { name: "Bacardi Rum", unit: "bottle", par: 3 },
        { name: "Patrón Silver Tequila", unit: "bottle", par: 4 },
        { name: "Maker's Mark Bourbon", unit: "bottle", par: 4 },
        { name: "Woodford Reserve", unit: "bottle", par: 4 },
        { name: "Johnnie Walker Black", unit: "bottle", par: 3 },
        { name: "Hennessy VSOP", unit: "bottle", par: 3 },
        { name: "Vermouth — Dry/Sweet", unit: "bottle", par: 6 },
      ],
    },
    {
      name: "Bar — Wine & Beer",
      sortOrder: 7,
      items: [
        { name: "BTG Red (rolling)", unit: "bottle", par: 30 },
        { name: "BTG White (rolling)", unit: "bottle", par: 24 },
        { name: "Sparkling Brut", unit: "bottle", par: 18 },
        { name: "Italian Cellar (spot check)", unit: "bottle", par: 60 },
        { name: "Draft Lines (kegs)", unit: "each", par: 4 },
        { name: "Bottled Beer (assorted)", unit: "case", par: 5 },
      ],
    },
    {
      name: "Pastry & Dessert",
      sortOrder: 8,
      items: [
        { name: "Valrhona Chocolate", unit: "lb", par: 6 },
        { name: "Key Lime Pie (whole)", unit: "each", par: 6 },
        { name: "Red Velvet Cake (whole)", unit: "each", par: 4 },
        { name: "Soft Serve Mix", unit: "gal", par: 3 },
        { name: "Vanilla Ice Cream", unit: "gal", par: 3 },
        { name: "Graham Cracker Crumb", unit: "lb", par: 3 },
      ],
    },
  ],
};
