import type { RestaurantSeed } from "./types";

export const miami: RestaurantSeed = {
  slug: "miami",
  menus: [
    {
      service: "Dinner",
      sections: [
        {
          name: "Caviar & Snacks",
          items: [
            {
              name: "Chips & Dip — Umai Kaluga Caviar",
              components: ["Umai Kaluga caviar", "house potato chips", "caramelized onion", "Florida sour cream", "chives"],
            },
            {
              name: "N25 Ossetra Caviar",
              components: ["N25 Ossetra caviar", "crème fraîche", "blinis"],
            },
            {
              name: "Sullivan Street Sourdough Bread",
              components: ["Sullivan Street sourdough", "sheep's milk ricotta", "honey", "thyme"],
            },
          ],
        },
        {
          name: "Soups & Salads",
          items: [
            {
              name: "Gioia Salad",
              components: ["baby gem", "endives", "radicchio", "red bell peppers", "tomatoes", "white balsamic vinaigrette"],
            },
            {
              name: "Basil Caesar",
              components: ["romaine", "basil", "lemon", "anchovy", "croutons", "Piave Vecchio cheese"],
            },
            {
              name: "Farmer Mike's Iceberg Wedge",
              components: ["iceberg", "crispy onions", "bacon", "tomatoes", "Valdeón blue cheese dressing"],
            },
          ],
        },
        {
          name: "Raw Bar",
          items: [
            { name: "Serenoa Skipper Sweet Oysters", components: ["Serenoa oysters", "passion fruit mignonette", "Bacardi rum cocktail sauce"] },
            { name: "Black Tiger Shrimp Cocktail", components: ["black tiger shrimp", "cocktail sauce"] },
            { name: "Cobia Ceviche", components: ["cobia", "leche de tigre", "habanero", "crispy chickpeas"] },
            { name: "Hamachi Crudo & Strawberries", components: ["hamachi", "strawberries", "avocado-mint mousse", "navel oranges", "Gioia EVOO"] },
            { name: "Wagyu & Pearls", components: ["Arrowhead wagyu tartare", "black garlic aioli", "Kaluga caviar", "sourdough toast"] },
            { name: "Yellowfin Tuna Tartare", components: ["yellowfin tuna", "pine nuts", "lemon oil", "Calabrian chili", "mint"] },
          ],
        },
        {
          name: "Appetizers",
          items: [
            { name: "Serenoa Oysters Rockefeller", components: ["Serenoa oysters", "watercress", "Malabar spinach", "Parmigiano Reggiano"] },
            { name: "Buffalo Mozzarella & Caviar", components: ["buffalo mozzarella", "Kaluga caviar", "zucchini", "basil", "Gioia EVOO"] },
            { name: "Foie Gras Crème Brûlée", components: ["Hudson Valley foie gras", "cashews", "toasted coconut", "mango"] },
            { name: "Sausage & Peppers", components: ["Sunshine Provisions fennel sausage", "Swank Farms Jimmy Nardello peppers", "Tiny Farms arugula"] },
            { name: "Suwannee River Wagyu Meatball", components: ["Suwannee wagyu", "burrata", "provolone", "pomodoro", "basil"] },
            { name: "Florida Blue Crab Cake", components: ["Florida blue crab", "Kaluga caviar", "Beacon Fisheries rock shrimp", "Meyer lemon", "crème fraîche"] },
          ],
        },
        {
          name: "Signature Pastas",
          items: [
            { name: "Lobster Fra Diavolo", components: ["1.5 lb Maine lobster", "cherry tomatoes", "Monograno linguine", "Gioia EVOO"] },
          ],
        },
        {
          name: "Steak & Chops",
          items: [
            { name: "Stone Axe Wagyu Flat Iron (8oz)" },
            { name: "Sir Harry Hanger Steak (10oz)" },
            { name: "Margaret River Wagyu NY Strip (14oz)" },
            { name: "Mayura Station Wagyu NY Strip (12oz)" },
            { name: "Margaret River Wagyu Tomahawk (32oz)" },
            { name: "Demkota Prime Filet Mignon (8oz)" },
            { name: "Demkota Prime Porterhouse (36oz)" },
            { name: "Upper Iowa Prime NY Strip (16oz)" },
            { name: "Greater Omaha Dry-Aged Cowboy Ribeye (22oz)" },
            { name: "Providence Grassfed Kansas City (20oz)" },
            { name: "Gundagai Lamb Chops (16oz)" },
            { name: "Rosewood Ranch Wagyu Porterhouse (32oz)" },
            { name: "Highland Hollow Txuleton (32oz)" },
            { name: "Highland Hollow Kansas City (36oz)" },
          ],
        },
        {
          name: "Steak Enhancements",
          items: [
            { name: "Exotic Peppercorn Sauce" },
            { name: "Truffle Butter" },
            { name: "Chimichurri" },
            { name: "Béarnaise" },
            { name: "Foie Gras Rossini" },
          ],
        },
        {
          name: "Land",
          items: [
            { name: "Farmer Mike's Zucchini Tataki", components: ["zucchini", "zucchini crema", "Parmigiano cream", "balsamico di Modena"] },
            { name: "Providence Cattle Braised Beef Short Rib", components: ["short rib", "potato fonduta", "Gratitude Farms mushrooms"] },
          ],
        },
        {
          name: "Sea",
          items: [
            { name: "Florida Keys Red Snapper", components: ["red snapper", "couscous", "fennel", "zucchini", "Sun Gold tomato", "pepper sauce"] },
            { name: "Sesame Crusted Yellowfin Tuna", components: ["yellowfin tuna", "confit fennel", "Campari tomatoes", "Cerignola olives"] },
            { name: "Grilled Canary Island Branzino", components: ["branzino", "lemon", "endive salad"] },
            { name: "Dover Sole", components: ["Dover sole", "capers", "chives", "parsley", "lemon", "brown butter"] },
          ],
        },
        {
          name: "Sides",
          items: [
            { name: "Madrid Salad", components: ["spring onions", "Gioia EVOO", "lemon"] },
            { name: "Florida Rosemary Fries", components: ["fries", "Parmigiano", "onion ketchup", "rosemary"] },
            { name: "Corn Pudding", components: ["sweet corn", "crème fraîche"] },
            { name: "Crimini Mushrooms", components: ["crimini", "shallots", "short rib jus", "red wine"] },
            { name: "Creamed Spinach", components: ["Malabar spinach", "brown garlic béchamel"] },
            { name: "Twice Baked Potato", components: ["potato", "sour cream", "chives"] },
            { name: "Grilled Asparagus", components: ["asparagus", "lemon", "EVOO"] },
            { name: "Maine Lobster Mac & Cheese", components: ["lumachine", "Gruyère", "aged cheddar", "Parmesan", "Red Leicester", "Maine lobster"] },
            { name: "Mezze Rigate Vodka Pasta", components: ["mezze rigate", "Grey Goose vodka", "pomodoro", "basil"] },
            { name: "Truffled Potato Fonduta", components: ["potato", "black winter truffle", "cultured butter"] },
          ],
        },
      ],
    },
  ],
  stations: [
    {
      name: "Walk-in Cooler — Proteins",
      sortOrder: 1,
      items: [
        { name: "Stone Axe Wagyu Flat Iron", unit: "lb", par: 6, category: "Beef" },
        { name: "Sir Harry Hanger Steak", unit: "lb", par: 5, category: "Beef" },
        { name: "Margaret River Wagyu NY Strip", unit: "lb", par: 10, category: "Beef" },
        { name: "Mayura Wagyu NY Strip", unit: "lb", par: 8, category: "Beef" },
        { name: "Margaret River Wagyu Tomahawk", unit: "each", par: 6, category: "Beef" },
        { name: "Demkota Prime Filet Mignon (8oz)", unit: "each", par: 24, category: "Beef" },
        { name: "Demkota Prime Porterhouse", unit: "each", par: 8, category: "Beef" },
        { name: "Upper Iowa Prime NY Strip", unit: "lb", par: 12, category: "Beef" },
        { name: "Greater Omaha Dry-Aged Cowboy Ribeye", unit: "each", par: 10, category: "Beef" },
        { name: "Providence Grassfed Kansas City", unit: "lb", par: 8, category: "Beef" },
        { name: "Rosewood Wagyu Porterhouse", unit: "each", par: 4, category: "Beef" },
        { name: "Highland Hollow Txuleton", unit: "each", par: 4, category: "Beef" },
        { name: "Highland Hollow Kansas City", unit: "each", par: 4, category: "Beef" },
        { name: "Gundagai Lamb Chops", unit: "lb", par: 6, category: "Lamb" },
        { name: "Suwannee River Wagyu Ground", unit: "lb", par: 8, category: "Beef" },
        { name: "Arrowhead Wagyu (tartare)", unit: "lb", par: 4, category: "Beef" },
        { name: "Providence Short Rib", unit: "lb", par: 10, category: "Beef" },
        { name: "Hudson Valley Foie Gras", unit: "lb", par: 3, category: "Specialty" },
        { name: "Sunshine Provisions Fennel Sausage", unit: "lb", par: 4, category: "Charcuterie" },
      ],
    },
    {
      name: "Walk-in Cooler — Seafood & Raw Bar",
      sortOrder: 2,
      items: [
        { name: "Serenoa Skipper Sweet Oysters", unit: "case", par: 4, category: "Shellfish" },
        { name: "Black Tiger Shrimp", unit: "lb", par: 6, category: "Shellfish" },
        { name: "Beacon Fisheries Rock Shrimp", unit: "lb", par: 4, category: "Shellfish" },
        { name: "Maine Lobster (1.5 lb)", unit: "each", par: 12, category: "Shellfish" },
        { name: "Florida Blue Crab Meat", unit: "lb", par: 4, category: "Shellfish" },
        { name: "Hamachi", unit: "lb", par: 4, category: "Fish" },
        { name: "Yellowfin Tuna", unit: "lb", par: 6, category: "Fish" },
        { name: "Cobia", unit: "lb", par: 4, category: "Fish" },
        { name: "Florida Keys Red Snapper", unit: "lb", par: 6, category: "Fish" },
        { name: "Canary Island Branzino", unit: "each", par: 12, category: "Fish" },
        { name: "Dover Sole", unit: "each", par: 8, category: "Fish" },
        { name: "Umai Kaluga Caviar", unit: "oz", par: 8, category: "Caviar" },
        { name: "N25 Ossetra Caviar", unit: "oz", par: 6, category: "Caviar" },
        { name: "Kaluga Caviar (service tin)", unit: "oz", par: 12, category: "Caviar" },
      ],
    },
    {
      name: "Walk-in Cooler — Dairy & Produce",
      sortOrder: 3,
      items: [
        { name: "Buffalo Mozzarella", unit: "lb", par: 6, category: "Cheese" },
        { name: "Burrata", unit: "each", par: 12, category: "Cheese" },
        { name: "Parmigiano Reggiano", unit: "lb", par: 8, category: "Cheese" },
        { name: "Piave Vecchio", unit: "lb", par: 3, category: "Cheese" },
        { name: "Valdeón Blue Cheese", unit: "lb", par: 3, category: "Cheese" },
        { name: "Cave-Aged Gruyère", unit: "lb", par: 4, category: "Cheese" },
        { name: "Aged Cheddar", unit: "lb", par: 4, category: "Cheese" },
        { name: "Red Leicester", unit: "lb", par: 2, category: "Cheese" },
        { name: "Provolone", unit: "lb", par: 3, category: "Cheese" },
        { name: "Sheep's Milk Ricotta", unit: "lb", par: 2, category: "Cheese" },
        { name: "Crème Fraîche", unit: "qt", par: 3, category: "Dairy" },
        { name: "Florida Sour Cream", unit: "qt", par: 3, category: "Dairy" },
        { name: "Cultured Butter", unit: "lb", par: 8, category: "Dairy" },
        { name: "Heavy Cream", unit: "qt", par: 6, category: "Dairy" },
        { name: "Eggs", unit: "case", par: 4, category: "Dairy" },
        { name: "Baby Gem Lettuce", unit: "case", par: 2, category: "Produce" },
        { name: "Endives", unit: "case", par: 1, category: "Produce" },
        { name: "Radicchio", unit: "case", par: 1, category: "Produce" },
        { name: "Iceberg Lettuce", unit: "case", par: 1, category: "Produce" },
        { name: "Tiny Farms Arugula", unit: "lb", par: 4, category: "Produce" },
        { name: "Malabar Spinach", unit: "lb", par: 4, category: "Produce" },
        { name: "Watercress", unit: "lb", par: 2, category: "Produce" },
        { name: "Cherry Tomatoes", unit: "case", par: 1, category: "Produce" },
        { name: "Campari Tomatoes", unit: "case", par: 1, category: "Produce" },
        { name: "Sun Gold Tomatoes", unit: "lb", par: 4, category: "Produce" },
        { name: "Swank Farms Jimmy Nardello Peppers", unit: "lb", par: 3, category: "Produce" },
        { name: "Red Bell Peppers", unit: "case", par: 1, category: "Produce" },
        { name: "Farmer Mike's Zucchini", unit: "case", par: 1, category: "Produce" },
        { name: "Asparagus", unit: "lb", par: 8, category: "Produce" },
        { name: "Gratitude Farms Crimini Mushrooms", unit: "lb", par: 6, category: "Produce" },
        { name: "Florida Sweet Corn", unit: "case", par: 1, category: "Produce" },
        { name: "Idaho Potatoes", unit: "case", par: 2, category: "Produce" },
        { name: "Black Winter Truffle", unit: "oz", par: 4, category: "Specialty" },
        { name: "Meyer Lemons", unit: "case", par: 1, category: "Produce" },
        { name: "Lemons", unit: "case", par: 2, category: "Produce" },
        { name: "Navel Oranges", unit: "case", par: 1, category: "Produce" },
        { name: "Strawberries", unit: "case", par: 1, category: "Produce" },
        { name: "Mango", unit: "case", par: 1, category: "Produce" },
        { name: "Basil", unit: "lb", par: 1, category: "Herbs" },
        { name: "Mint", unit: "lb", par: 1, category: "Herbs" },
        { name: "Chives", unit: "lb", par: 1, category: "Herbs" },
        { name: "Thyme", unit: "lb", par: 1, category: "Herbs" },
        { name: "Parsley", unit: "lb", par: 1, category: "Herbs" },
        { name: "Rosemary", unit: "lb", par: 1, category: "Herbs" },
      ],
    },
    {
      name: "Walk-in Freezer",
      sortOrder: 4,
      items: [
        { name: "Sullivan Street Sourdough (par-baked)", unit: "case", par: 2 },
        { name: "Blinis (frozen)", unit: "case", par: 1 },
        { name: "Vanilla Ice Cream", unit: "gal", par: 4 },
        { name: "Soft Serve Mix", unit: "gal", par: 3 },
      ],
    },
    {
      name: "Dry Storage",
      sortOrder: 5,
      items: [
        { name: "GIOIA Hospitality Extra Virgin Olive Oil", unit: "l", par: 12, category: "Oils" },
        { name: "Lemon Oil", unit: "l", par: 2, category: "Oils" },
        { name: "Truffle Oil", unit: "l", par: 1, category: "Oils" },
        { name: "Canola Blend", unit: "gal", par: 6, category: "Oils" },
        { name: "Balsamico di Modena", unit: "l", par: 3, category: "Vinegars" },
        { name: "White Balsamic", unit: "l", par: 3, category: "Vinegars" },
        { name: "Monograno Linguine", unit: "lb", par: 20, category: "Pasta" },
        { name: "Lumachine Pasta", unit: "lb", par: 16, category: "Pasta" },
        { name: "Mezze Rigate", unit: "lb", par: 16, category: "Pasta" },
        { name: "Orecchiette", unit: "lb", par: 12, category: "Pasta" },
        { name: "Couscous", unit: "lb", par: 8, category: "Grains" },
        { name: "Pine Nuts", unit: "lb", par: 4, category: "Nuts" },
        { name: "Cashews", unit: "lb", par: 3, category: "Nuts" },
        { name: "Toasted Coconut", unit: "lb", par: 2, category: "Pantry" },
        { name: "Cerignola Olives", unit: "lb", par: 4, category: "Pantry" },
        { name: "Capers", unit: "lb", par: 2, category: "Pantry" },
        { name: "Calabrian Chili", unit: "lb", par: 2, category: "Pantry" },
        { name: "Anchovies", unit: "lb", par: 2, category: "Pantry" },
        { name: "Crispy Chickpeas", unit: "lb", par: 3, category: "Pantry" },
        { name: "Black Peppercorn (mixed exotic)", unit: "lb", par: 2, category: "Spices" },
        { name: "Sea Salt", unit: "lb", par: 10, category: "Spices" },
        { name: "All-Purpose Flour", unit: "lb", par: 50, category: "Baking" },
        { name: "Sugar", unit: "lb", par: 25, category: "Baking" },
        { name: "Honey", unit: "qt", par: 2, category: "Baking" },
      ],
    },
    {
      name: "Bar — Liquor",
      sortOrder: 6,
      items: [
        { name: "Grey Goose Vodka (1L)", unit: "bottle", par: 8 },
        { name: "Bacardi Rum (1L)", unit: "bottle", par: 4 },
        { name: "Fiola Cask Bourbon", unit: "bottle", par: 4 },
        { name: "Tequila Blanco (well)", unit: "bottle", par: 6 },
        { name: "Gin (well)", unit: "bottle", par: 4 },
        { name: "Vermouth — Dry", unit: "bottle", par: 4 },
        { name: "Vermouth — Sweet", unit: "bottle", par: 4 },
        { name: "Cognac VSOP", unit: "bottle", par: 3 },
        { name: "Amaro Selection (Montenegro/Nonino)", unit: "bottle", par: 4 },
      ],
    },
    {
      name: "Bar — Wine & Beer",
      sortOrder: 7,
      items: [
        { name: "By-the-Glass Reds (rolling)", unit: "bottle", par: 36, notes: "Across 8-12 SKUs" },
        { name: "By-the-Glass Whites", unit: "bottle", par: 24 },
        { name: "Sparkling Brut", unit: "bottle", par: 18 },
        { name: "Champagne (reserve)", unit: "bottle", par: 12 },
        { name: "Italian Reds (cellar rotation)", unit: "bottle", par: 60, notes: "Sample for spot-check; full count separate" },
        { name: "Draft Lines", unit: "each", par: 4, notes: "Spot check kegs at change" },
        { name: "Bottled Beer (assorted)", unit: "case", par: 6 },
      ],
    },
    {
      name: "Pastry & Dessert",
      sortOrder: 8,
      items: [
        { name: "Valrhona Chocolate", unit: "lb", par: 6 },
        { name: "Soft Serve Sundae Mix", unit: "gal", par: 3 },
        { name: "Key Lime Pie (whole)", unit: "each", par: 6 },
        { name: "Red Velvet Cake (whole)", unit: "each", par: 4 },
      ],
    },
  ],
};
